-- 初始化 PostgreSQL + pgvector。
-- Java 开发者对照：这个脚本类似 Spring Boot 首次启动时执行 schema.sql。

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_chat_id_id
ON chat_messages (chat_id, id);

-- 预留 pgvector 示例表，后续做语义记忆 / RAG 时可直接复用。
-- 当前代码不会写入该表，只先确保 vector 扩展和向量类型可用。
CREATE TABLE IF NOT EXISTS chat_message_embeddings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    embedding vector(1536),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_message_embeddings_message_id
ON chat_message_embeddings (message_id);
